-- H2 2.1.214;
;             
CREATE USER IF NOT EXISTS "STUDENT" SALT 'ff763707533514ef' HASH 'de2d50d1fa63680c735150704feb5a9da02fb09c17c59fa06a5c8936a9637f0d' ADMIN;    
CREATE CACHED TABLE "PUBLIC"."PODATAK"(
    "ID" BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1 RESTART WITH 65) NOT NULL,
    "VRSTA" CHARACTER VARYING(100) NOT NULL,
    "BROJNOST" INTEGER NOT NULL,
    "SPOL" CHARACTER VARYING(10) NOT NULL,
    "KOMENTARI" CHARACTER VARYING(255),
    "ISTRAZIVAC" CHARACTER VARYING(255) NOT NULL,
    "LOKACIJA" CHARACTER VARYING(100) NOT NULL,
    "DATUM" DATE NOT NULL
);         
ALTER TABLE "PUBLIC"."PODATAK" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");      
-- 13 +/- SELECT COUNT(*) FROM PUBLIC.PODATAK;
INSERT INTO "PUBLIC"."PODATAK"("ID", "VRSTA", "BROJNOST", "SPOL", "KOMENTARI", "ISTRAZIVAC", "LOKACIJA", "DATUM") OVERRIDING SYSTEM VALUE VALUES(1, 'velika_sjenica', 3, 'Unknown', 'pjeva u parku', 'Ljiljana Becmenica', 'Ucka', DATE '2023-05-04');        
INSERT INTO "PUBLIC"."PODATAK"("ID", "VRSTA", "BROJNOST", "SPOL", "KOMENTARI", "ISTRAZIVAC", "LOKACIJA", "DATUM") OVERRIDING SYSTEM VALUE VALUES(2, 'zeba', 4, 'Unknown', '', 'Ana Medic', 'Mljet', DATE '2021-04-04');       
INSERT INTO "PUBLIC"."PODATAK"("ID", "VRSTA", "BROJNOST", "SPOL", "KOMENTARI", "ISTRAZIVAC", "LOKACIJA", "DATUM") OVERRIDING SYSTEM VALUE VALUES(3, 'skanjac', 1, 'Male', 'prelet', 'Luka Lovrinovic', 'Mljet', DATE '0202-03-02');           
INSERT INTO "PUBLIC"."PODATAK"("ID", "VRSTA", "BROJNOST", "SPOL", "KOMENTARI", "ISTRAZIVAC", "LOKACIJA", "DATUM") OVERRIDING SYSTEM VALUE VALUES(4, 'zelendur', 3, 'Unknown', 'pjeva', 'Ana Medic', 'Ucka', DATE '2023-03-07');               
INSERT INTO "PUBLIC"."PODATAK"("ID", "VRSTA", "BROJNOST", "SPOL", "KOMENTARI", "ISTRAZIVAC", "LOKACIJA", "DATUM") OVERRIDING SYSTEM VALUE VALUES(5, 'divlja_patka', 2, 'Female', 'prelet', 'Luka Lovrinovic', 'Savica', DATE '2022-06-06');   
INSERT INTO "PUBLIC"."PODATAK"("ID", "VRSTA", "BROJNOST", "SPOL", "KOMENTARI", "ISTRAZIVAC", "LOKACIJA", "DATUM") OVERRIDING SYSTEM VALUE VALUES(6, 'zeba', 2, 'Female', '', 'Ljiljana Becmenica', 'Savica', DATE '2023-05-04');              
INSERT INTO "PUBLIC"."PODATAK"("ID", "VRSTA", "BROJNOST", "SPOL", "KOMENTARI", "ISTRAZIVAC", "LOKACIJA", "DATUM") OVERRIDING SYSTEM VALUE VALUES(7, 'kos', 2, 'Male', 'pjeva', 'Sanda Katic', 'Palud', DATE '2020-01-04');    
INSERT INTO "PUBLIC"."PODATAK"("ID", "VRSTA", "BROJNOST", "SPOL", "KOMENTARI", "ISTRAZIVAC", "LOKACIJA", "DATUM") OVERRIDING SYSTEM VALUE VALUES(8, 'kos', 3, 'Unknown', '', 'Ana Medic', 'Savica', DATE '2023-03-07');       
INSERT INTO "PUBLIC"."PODATAK"("ID", "VRSTA", "BROJNOST", "SPOL", "KOMENTARI", "ISTRAZIVAC", "LOKACIJA", "DATUM") OVERRIDING SYSTEM VALUE VALUES(9, 'zelendur', 1, 'Unknown', 'pjeva', 'Ljiljana Becmenica', 'Savica', DATE '2022-06-14');    
INSERT INTO "PUBLIC"."PODATAK"("ID", "VRSTA", "BROJNOST", "SPOL", "KOMENTARI", "ISTRAZIVAC", "LOKACIJA", "DATUM") OVERRIDING SYSTEM VALUE VALUES(10, 'velika_sjenica', 2, 'Female', 'pjeva u parku', 'Luka Lovrinovic', 'Mljet', DATE '2021-04-06');          
INSERT INTO "PUBLIC"."PODATAK"("ID", "VRSTA", "BROJNOST", "SPOL", "KOMENTARI", "ISTRAZIVAC", "LOKACIJA", "DATUM") OVERRIDING SYSTEM VALUE VALUES(12, 'golub_grivnjas', 4, 'Unknown', '', 'Borna Lasrek', 'Savica', DATE '2023-05-02');        
INSERT INTO "PUBLIC"."PODATAK"("ID", "VRSTA", "BROJNOST", "SPOL", "KOMENTARI", "ISTRAZIVAC", "LOKACIJA", "DATUM") OVERRIDING SYSTEM VALUE VALUES(33, 'golub_grivnjas', 2, 'Unknown', '', 'Ana Medic', 'Savica', DATE '2023-05-30');           
INSERT INTO "PUBLIC"."PODATAK"("ID", "VRSTA", "BROJNOST", "SPOL", "KOMENTARI", "ISTRAZIVAC", "LOKACIJA", "DATUM") OVERRIDING SYSTEM VALUE VALUES(34, 'kos', 3, 'Female', '', 'Ana Medic', 'Ucka', DATE '2023-05-30');         
